# 基本设置
title: sddtc
author: sddtc

# 菜单
menu:
  - title: 首页
    url: /
  - title: 我的简历
    url: /pages/resume.html

# 页面设置
baseurl: '/blog-alpha'

# 主题
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock']