baseurl: ''

title: blog-alpha
author: sddtc

# 菜单
menu:
  - title: 首页
    url: /blog-alpha
  - title: 我的简历
    url: /blog-alpha/pages/resume.html
  - title: 我的旅行
    url: /blog-alpha/pages/tour.html
  - title: 我的宠物
    url: /blog-alpha/pages/pets.html