baseurl: ''

title: blog-alpha
author: sddtc

# 菜单
menu:
  - title: 首页
    url: /
  - title: 我的简历
    url: /pages/resume.html
  - title: 我的旅行
    url: /pages/tour.html
  - title: 我的宠物
    url: /pages/pets.html